<a href="https://colab.research.google.com/github/ianxdxd/Couting-occurences-using-numpy/blob/main/numpy__matrix_3x3_2x10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

m = np.matrix([[1,1,3], [4,5,2], [3,0,0]]) # primary matrix, used for obtaining the values
print("Original Matrix: ") # print original matrix
print(m)

# get flattened array:
arr = m.getA1()
# get the bincounts:
bc = np.bincount(arr)

print("Occurences: ")
print(bc)
 

Original Matrix: 
[[1 1 3]
 [4 5 2]
 [3 0 0]]
Occurences: 
[2 2 1 2 1 1]
